runtime: python

# the PROJECT-DIRECTORY is the one with settings.py and wsgi.py
entrypoint: gunicorn -b :$PORT localcontexts.wsgi # specific to a GUnicorn HTTP server deployment
env: flex # for Google Cloud Flexible App Engine

network:
  name: anth-ja77-local-contexts-net
  subnetwork_name: anth-ja77-local-contexts-subnet-01

# any environment variables you want to pass to your application.
# accessible through os.environ['VARIABLE_NAME']
env_variables:
# the secret key used for the Django app (from PROJECT-DIRECTORY/settings.py)
  PROD_KEY: 'fd*6ku_=^#nu8o6)@j3-sz9zhlwf!j-b#oy7&tdyn6tx=4*y0h' 
  DEBUG_VALUE: 'False' # always False for deployment
  
# everything after /cloudsql/ can be found by entering >> gcloud sql instances describe DATABASE-NAME << in your Terminal
# the DATABASE-NAME is the name you gave your project's PostgreSQL database
# the second line from the describe output called connectionName can be copied and pasted after /cloudsql/
  DB_HOST: '/cloudsql/anth-ja77-local-contexts-435e:us-west1:localcontextsdb'
  DB_PORT: '5432' # PostgreSQL port
  DB_NAME: 'localcontextsdb'
  DB_USER: 'dianalovette' # either 'postgres' (default) or one you created on the PostgreSQL instance page
  DB_PASS: 'theMe@tloaf'
  
  STATIC_URL: 'https://storage.googleapis.com/local-contexts-static/static/' # this is the url that you sync static files to
  MEDIA_URL: 'https://storage.googleapis.com/local-contexts-media/media/'

  SITE_ADMIN_NAME: "Diana"
  SITE_ADMIN_EMAIL: "dianalovette90@gmail.com"

  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_HOST_USER: "dev.test.mail.000@gmail.com"
  EMAIL_HOST_PASSWORD: "lvbyjfbgdtcbshru"

  USE_GCP: 'True'

handlers:
- url: /static
  static_dir: static

beta_settings:
# from command >> gcloud sql instances describe DATABASE-NAME <<
  cloud_sql_instances: anth-ja77-local-contexts-435e:us-west1:localcontextsdb 

runtime_config:
  python_version: 3 # enter your Python version BASE ONLY here. Enter 2 for 2.7.9 or 3 for 3.6.4